name: dart_mapbox_search
description: 'A Dart package for the Mapbox Search Box and Geocoding APIs.'
version: 1.0.0
repository: https://github.com/scialapp/dart_mapbox_search

homepage: https://github.com/scialapp/dart_mapbox_search

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.1
  uuid: ^4.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
